name: ci-golang-workflow
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      ## Rodando uma action para configurar o ambiente de execução
      - uses: actions/checkout@v2 ## Baixa os arquivos do repositório para o ambiente de execução
      - name: Set up Go 1.18
        uses: actions/setup-go@v2 ## Configura o ambiente de execução para usar a versão 1.18 do Go
        with:
          go-version: 1.18
      ## Executando os comandos para construir e testar a aplicação
      - name: Build and test
        run: |
          go test
          go run math.go